
##################################################
###   Visit https://github.com/tinybirdco/ci   ###
###   for more details or custom CI/CD         ###
##################################################

name: Tinybird - CI Workflow

on:
    workflow_dispatch:
    pull_request:
    paths:
        - 'change_column_type_to_lowcardinality/**'
    branches:
        - main
    types: [opened, reopened, labeled, unlabeled, synchronize, closed]

concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
    ci:
        uses: tinybirdco/ci/.github/workflows/ci.yml@main
        with:
        data_project_dir: ./change_column_type_to_lowcardinality
        secrets:
        tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_CHANGE_COLUMN_TYPE_TO_LOW_CARDINALITY }}
        tb_host: https://api.tinybird.co