name: Tinybird - CI Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    types: [opened, reopened, labeled, unlabeled, synchronize, closed]

concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
  add_new_column_to_a_materialized_view:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './add_new_column_to_a_materialized_view'
    services:
      tinybird:
        image: tinybirdco/tinybird-local:beta
        ports:
          - 80:80
    steps:
      - uses: actions/checkout@v3
      - name: Install Tinybird CLI
        run: curl -LsSf https://api.tinybird.co/static/install.sh | sh
      - name: Build project
        run: tb build
      - name: Test project
        run: tb test run
      - name: deploy project
        run: tb deployment create --auto --wait
      - name: push some data
        run: tb datasource append analytics_events fixtures/analytics_events.ndjson
      - name: check data in the MV
        run: tb sql "select * from analytics_sessions_mv1"
      - name: apply patch
        run: cp -r .diff/* . && git diff
      - name: deploy project again
        run: tb deployment create --auto --wait
      - name: check data in the MV after deploy
        run: tb sql "select * from analytics_sessions_mv1"

